// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLzzYzckUQ6CyqeTNw2lwn2Ke21WZUKNc',
    appId: '1:802751393856:web:494ce400433cbe5ad42fa5',
    messagingSenderId: '802751393856',
    projectId: 'movies-cfc34',
    authDomain: 'movies-cfc34.firebaseapp.com',
    storageBucket: 'movies-cfc34.appspot.com',
    measurementId: 'G-8XEZGM4PK1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW4QlgGth4gfekYrWevT7RoUo6TSH2kS8',
    appId: '1:802751393856:android:7e5c50585be07b68d42fa5',
    messagingSenderId: '802751393856',
    projectId: 'movies-cfc34',
    storageBucket: 'movies-cfc34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpmv21_F9FxM9x33EQxH8RAxA0cm8f1Yg',
    appId: '1:802751393856:ios:6592976ed100ae51d42fa5',
    messagingSenderId: '802751393856',
    projectId: 'movies-cfc34',
    storageBucket: 'movies-cfc34.appspot.com',
    iosBundleId: 'com.example.tpAvisFilm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpmv21_F9FxM9x33EQxH8RAxA0cm8f1Yg',
    appId: '1:802751393856:ios:6592976ed100ae51d42fa5',
    messagingSenderId: '802751393856',
    projectId: 'movies-cfc34',
    storageBucket: 'movies-cfc34.appspot.com',
    iosBundleId: 'com.example.tpAvisFilm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLzzYzckUQ6CyqeTNw2lwn2Ke21WZUKNc',
    appId: '1:802751393856:web:cb9bfa6b07994ce2d42fa5',
    messagingSenderId: '802751393856',
    projectId: 'movies-cfc34',
    authDomain: 'movies-cfc34.firebaseapp.com',
    storageBucket: 'movies-cfc34.appspot.com',
    measurementId: 'G-2Y35Y8QTGK',
  );
}
